# test-flake-bundle — Minimal flake for testing `snix build .#hello` on Redox
#
# Contains:
#   - flake.nix: outputs a hello-world Rust package
#   - flake.lock: uses a path-type input (no HTTP needed)
#   - src/: Rust source for a hello binary
#   - build-hello.sh: builder script invoked by the derivation
#
# The flake uses a `path`-type input pointing to "./src" so the entire
# test works offline without network access.

{ pkgs, rustToolchain ? null }:

pkgs.runCommand "test-flake-bundle" { } ''
  mkdir -p $out/src

  # ── Rust source ─────────────────────────────────────────────────
  mkdir -p $out/src/src
  cat > $out/src/Cargo.toml << 'TOML'
[package]
name = "hello-flake"
version = "0.1.0"
edition = "2021"
TOML

  cat > $out/src/src/main.rs << 'RUST'
fn main() {
    println!("Hello from flake!");
}
RUST

  cat > $out/src/Cargo.lock << 'LOCK'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "hello-flake"
version = "0.1.0"
LOCK

  # ── Builder scripts (bash — needs HOME and reliable relative paths) ──
  cat > $out/build-hello.sh << 'BUILDER'
#!/nix/system/profile/bin/bash
set -e
export PATH=/nix/system/profile/bin:/bin:/usr/bin
export LD_LIBRARY_PATH=/nix/system/profile/lib:/usr/lib/rustc:/lib
export HOME="$TMPDIR"
export CARGO_HOME="$TMPDIR/cargo-home"
export RUSTC=/nix/system/profile/bin/rustc
SYSROOT=$($RUSTC --print=sysroot)
export RUSTFLAGS="--sysroot $SYSROOT"
export CARGO_BUILD_TARGET=x86_64-unknown-redox
export CARGO_TARGET_X86_64_UNKNOWN_REDOX_LINKER=/nix/system/profile/bin/cc
export CARGO_TARGET_DIR="$TMPDIR/target"
mkdir -p "$CARGO_HOME" "$out/bin"
cargo build --offline --locked --manifest-path "$src/Cargo.toml" -j2 </dev/null
cp "$TMPDIR/target/x86_64-unknown-redox/debug/hello-flake" "$out/bin/hello"
BUILDER
  chmod +x $out/build-hello.sh

  cat > $out/build-file-probe.sh << 'BUILDER'
#!/nix/system/profile/bin/bash
set -e
printf 'FILE_PROBE_OK\n' > "$out"
BUILDER
  chmod +x $out/build-file-probe.sh

  # ── Tiny --file probe derivation ───────────────────────────────
  cat > $out/file-build.nix << 'NIX'
derivation {
  name = "file-probe";
  builder = "/nix/system/profile/bin/bash";
  args = [ "/usr/src/test-flake/build-file-probe.sh" ];
  system = "x86_64-unknown-redox";
}
NIX

  cat > $out/file-build-multiarg.nix << 'NIX'
derivation {
  name = "file-probe-multiarg";
  builder = "/nix/system/profile/bin/bash";
  args = [ "--noprofile" "--norc" "/usr/src/test-flake/build-file-probe.sh" ];
  system = "x86_64-unknown-redox";
}
NIX

  # ── flake.nix ──────────────────────────────────────────────────
  cat > $out/flake.nix << 'FLAKE'
{
  description = "Test flake for snix build validation";

  outputs = { self, ... }: {
    packages."x86_64-unknown-redox".hello = derivation {
      name = "hello-flake";
      builder = "/nix/system/profile/bin/bash";
      args = [ "''${builtins.toString self}/build-hello.sh" ];
      system = "x86_64-unknown-redox";
      src = "''${builtins.toString self}/src";
    };
  };
}
FLAKE

  # ── flake.lock ─────────────────────────────────────────────────
  # Minimal lock with no inputs (self-contained flake)
  cat > $out/flake.lock << 'LOCK'
{
  "version": 7,
  "root": "root",
  "nodes": {
    "root": {}
  }
}
LOCK
''
