// This file is @generated by prost-build.
/// PathInfo shows information about a Nix Store Path.
/// That's a single element inside /nix/store.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathInfo {
    /// The entry both describes the store path and the contents, which can be a
    /// directory, file or symlink.
    #[prost(message, optional, tag = "1")]
    pub entry: ::core::option::Option<::snix_castore::proto::Entry>,
    /// List of references (output path hashes)
    /// This really is the raw *bytes*, after decoding nixbase32, and not a
    /// base32-encoded string.
    #[prost(bytes = "bytes", repeated, tag = "2")]
    pub references: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    /// see below.
    #[prost(message, optional, tag = "3")]
    pub narinfo: ::core::option::Option<NarInfo>,
}
/// Represents a path in the Nix store (a direct child of STORE_DIR).
/// It is commonly formatted by a nixbase32-encoding the digest, and
/// concatenating the name, separated by a `-`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorePath {
    /// The string after digest and `-`.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The digest (20 bytes).
    #[prost(bytes = "bytes", tag = "2")]
    pub digest: ::prost::bytes::Bytes,
}
/// Nix C++ uses NAR (Nix Archive) as a format to transfer store paths,
/// and stores metadata and signatures in NARInfo files.
/// Store all these attributes in a separate message.
///
/// This is useful to render .narinfo files to clients, or to preserve/validate
/// these signatures.
/// As verifying these signatures requires the whole NAR file to be synthesized,
/// moving to another signature scheme is desired.
/// Even then, it still makes sense to hold this data, for old clients.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NarInfo {
    /// This size of the NAR file, in bytes.
    #[prost(uint64, tag = "1")]
    pub nar_size: u64,
    /// The sha256 of the NAR file representation.
    #[prost(bytes = "bytes", tag = "2")]
    pub nar_sha256: ::prost::bytes::Bytes,
    /// The signatures in a .narinfo file.
    #[prost(message, repeated, tag = "3")]
    pub signatures: ::prost::alloc::vec::Vec<nar_info::Signature>,
    /// A list of references. To validate .narinfo signatures, a fingerprint needs
    /// to be constructed.
    /// This fingerprint doesn't just contain the hashes of the output paths of all
    /// references (like PathInfo.references), but their whole (base)names, so we
    /// need to keep them somewhere.
    #[prost(string, repeated, tag = "4")]
    pub reference_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The StorePath of the .drv file producing this output.
    /// The .drv suffix is omitted in its `name` field.
    #[prost(message, optional, tag = "5")]
    pub deriver: ::core::option::Option<StorePath>,
    /// The CA field in the .narinfo.
    /// Its textual representations seen in the wild are one of the following:
    ///   - `fixed:r:sha256:1gcky5hlf5vqfzpyhihydmm54grhc94mcs8w7xr8613qsqb1v2j6`
    ///     fixed-output derivations using "recursive" `outputHashMode`.
    ///   - `fixed:sha256:19xqkh72crbcba7flwxyi3n293vav6d7qkzkh2v4zfyi4iia8vj8
    ///     fixed-output derivations using "flat" `outputHashMode`
    ///   - `text:sha256:19xqkh72crbcba7flwxyi3n293vav6d7qkzkh2v4zfyi4iia8vj8`
    ///     Text hashing, used for uploaded .drv files and outputs produced by
    ///     builtins.toFile.
    ///
    /// Semantically, they can be split into the following components:
    ///   - "content address prefix". Currently, "fixed" and "text" are supported.
    ///   - "hash mode". Currently, "flat" and "recursive" are supported.
    ///   - "hash type". The underlying hash function used.
    ///     Currently, sha1, md5, sha256, sha512.
    ///   - "digest". The digest itself.
    ///
    /// There are some restrictions on the possible combinations.
    /// For example, `text` and `fixed:recursive` always imply sha256.
    ///
    /// We use an enum to encode the possible combinations, and optimize for the
    /// common case, `fixed:recursive`, identified as `NAR_SHA256`.
    #[prost(message, optional, tag = "6")]
    pub ca: ::core::option::Option<nar_info::Ca>,
}
/// Nested message and enum types in `NARInfo`.
pub mod nar_info {
    /// This represents a (parsed) signature line in a .narinfo file.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Signature {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(bytes = "bytes", tag = "2")]
        pub data: ::prost::bytes::Bytes,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Ca {
        /// The hashing type used.
        #[prost(enumeration = "ca::Hash", tag = "1")]
        pub r#type: i32,
        /// The digest, in raw bytes.
        #[prost(bytes = "bytes", tag = "2")]
        pub digest: ::prost::bytes::Bytes,
    }
    /// Nested message and enum types in `CA`.
    pub mod ca {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Hash {
            /// produced when uploading fixed-output store paths using NAR-based
            /// hashing (`outputHashMode = "recursive"`).
            NarSha256 = 0,
            NarSha1 = 1,
            NarSha512 = 2,
            NarMd5 = 3,
            /// Produced when uploading .drv files or outputs produced by
            /// builtins.toFile.
            /// Produces equivalent digests as FLAT_SHA256, but is a separate
            /// hashing type in Nix, affecting output path calculation.
            TextSha256 = 4,
            /// Produced when using fixed-output derivations with
            /// `outputHashMode = "flat"`.
            FlatSha1 = 5,
            FlatMd5 = 6,
            FlatSha256 = 7,
            FlatSha512 = 8,
        }
        impl Hash {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::NarSha256 => "NAR_SHA256",
                    Self::NarSha1 => "NAR_SHA1",
                    Self::NarSha512 => "NAR_SHA512",
                    Self::NarMd5 => "NAR_MD5",
                    Self::TextSha256 => "TEXT_SHA256",
                    Self::FlatSha1 => "FLAT_SHA1",
                    Self::FlatMd5 => "FLAT_MD5",
                    Self::FlatSha256 => "FLAT_SHA256",
                    Self::FlatSha512 => "FLAT_SHA512",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "NAR_SHA256" => Some(Self::NarSha256),
                    "NAR_SHA1" => Some(Self::NarSha1),
                    "NAR_SHA512" => Some(Self::NarSha512),
                    "NAR_MD5" => Some(Self::NarMd5),
                    "TEXT_SHA256" => Some(Self::TextSha256),
                    "FLAT_SHA1" => Some(Self::FlatSha1),
                    "FLAT_MD5" => Some(Self::FlatMd5),
                    "FLAT_SHA256" => Some(Self::FlatSha256),
                    "FLAT_SHA512" => Some(Self::FlatSha512),
                    _ => None,
                }
            }
        }
    }
}
/// The parameters that can be used to lookup a (single) PathInfo object.
/// Currently, only a lookup by output hash is supported.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPathInfoRequest {
    #[prost(oneof = "get_path_info_request::ByWhat", tags = "1")]
    pub by_what: ::core::option::Option<get_path_info_request::ByWhat>,
}
/// Nested message and enum types in `GetPathInfoRequest`.
pub mod get_path_info_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ByWhat {
        /// The output hash of a nix path (20 bytes).
        /// This is the nixbase32-decoded portion of a Nix output path, so to substitute
        /// /nix/store/xm35nga2g20mz5sm5l6n8v3bdm86yj83-cowsay-3.04
        /// this field would contain nixbase32dec("xm35nga2g20mz5sm5l6n8v3bdm86yj83").
        #[prost(bytes, tag = "1")]
        ByOutputHash(::prost::bytes::Bytes),
    }
}
/// The parameters that can be used to lookup (multiple) PathInfo objects.
/// Currently no filtering is possible, all objects are returned.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListPathInfoRequest {}
/// CalculateNARResponse is the response returned by the CalculateNAR request.
///
/// It contains the size of the NAR representation (in bytes), and the sha56
/// digest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CalculateNarResponse {
    /// This size of the NAR file, in bytes.
    #[prost(uint64, tag = "1")]
    pub nar_size: u64,
    /// The sha256 of the NAR file representation.
    #[prost(bytes = "bytes", tag = "2")]
    pub nar_sha256: ::prost::bytes::Bytes,
}
/// Generated client implementations.
pub mod path_info_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PathInfoServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PathInfoServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PathInfoServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PathInfoServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PathInfoServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Return a PathInfo message matching the criteria specified in the
        /// GetPathInfoRequest message.
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPathInfoRequest>,
        ) -> std::result::Result<tonic::Response<super::PathInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.store.v1.PathInfoService/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.store.v1.PathInfoService", "Get"));
            self.inner.unary(req, path, codec).await
        }
        /// Upload a PathInfo object to the remote end. It MUST not return until the
        /// PathInfo object has been written on the the remote end.
        ///
        /// The remote end MAY check if a potential DirectoryNode has already been
        /// uploaded.
        ///
        /// Uploading clients SHOULD obviously not steer other machines to try to
        /// substitute before from the remote end before having finished uploading
        /// PathInfo, Directories and Blobs.
        /// The returned PathInfo object MAY contain additional narinfo signatures, but
        /// is otherwise left untouched.
        pub async fn put(
            &mut self,
            request: impl tonic::IntoRequest<super::PathInfo>,
        ) -> std::result::Result<tonic::Response<super::PathInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.store.v1.PathInfoService/Put",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.store.v1.PathInfoService", "Put"));
            self.inner.unary(req, path, codec).await
        }
        /// Calculate the NAR representation of the contents specified by the
        /// root_node. The calculation SHOULD be cached server-side for subsequent
        /// requests.
        ///
        /// All references (to blobs or Directory messages) MUST already exist in the
        /// store.
        ///
        /// The method can be used to produce a Nix fixed-output path, which contains
        /// the (compressed) sha256 of the NAR content representation in the root_node
        /// name (suffixed with the name).
        ///
        /// It can also be used to calculate arbitrary NAR hashes of output paths, in
        /// case a legacy Nix Binary Cache frontend is provided.
        pub async fn calculate_nar(
            &mut self,
            request: impl tonic::IntoRequest<::snix_castore::proto::Entry>,
        ) -> std::result::Result<
            tonic::Response<super::CalculateNarResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.store.v1.PathInfoService/CalculateNAR",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("snix.store.v1.PathInfoService", "CalculateNAR"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Return a stream of PathInfo messages matching the criteria specified in
        /// ListPathInfoRequest.
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPathInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PathInfo>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.store.v1.PathInfoService/List",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.store.v1.PathInfoService", "List"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod path_info_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PathInfoServiceServer.
    #[async_trait]
    pub trait PathInfoService: std::marker::Send + std::marker::Sync + 'static {
        /// Return a PathInfo message matching the criteria specified in the
        /// GetPathInfoRequest message.
        async fn get(
            &self,
            request: tonic::Request<super::GetPathInfoRequest>,
        ) -> std::result::Result<tonic::Response<super::PathInfo>, tonic::Status>;
        /// Upload a PathInfo object to the remote end. It MUST not return until the
        /// PathInfo object has been written on the the remote end.
        ///
        /// The remote end MAY check if a potential DirectoryNode has already been
        /// uploaded.
        ///
        /// Uploading clients SHOULD obviously not steer other machines to try to
        /// substitute before from the remote end before having finished uploading
        /// PathInfo, Directories and Blobs.
        /// The returned PathInfo object MAY contain additional narinfo signatures, but
        /// is otherwise left untouched.
        async fn put(
            &self,
            request: tonic::Request<super::PathInfo>,
        ) -> std::result::Result<tonic::Response<super::PathInfo>, tonic::Status>;
        /// Calculate the NAR representation of the contents specified by the
        /// root_node. The calculation SHOULD be cached server-side for subsequent
        /// requests.
        ///
        /// All references (to blobs or Directory messages) MUST already exist in the
        /// store.
        ///
        /// The method can be used to produce a Nix fixed-output path, which contains
        /// the (compressed) sha256 of the NAR content representation in the root_node
        /// name (suffixed with the name).
        ///
        /// It can also be used to calculate arbitrary NAR hashes of output paths, in
        /// case a legacy Nix Binary Cache frontend is provided.
        async fn calculate_nar(
            &self,
            request: tonic::Request<::snix_castore::proto::Entry>,
        ) -> std::result::Result<
            tonic::Response<super::CalculateNarResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the List method.
        type ListStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PathInfo, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Return a stream of PathInfo messages matching the criteria specified in
        /// ListPathInfoRequest.
        async fn list(
            &self,
            request: tonic::Request<super::ListPathInfoRequest>,
        ) -> std::result::Result<tonic::Response<Self::ListStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct PathInfoServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PathInfoServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PathInfoServiceServer<T>
    where
        T: PathInfoService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snix.store.v1.PathInfoService/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: PathInfoService>(pub Arc<T>);
                    impl<
                        T: PathInfoService,
                    > tonic::server::UnaryService<super::GetPathInfoRequest>
                    for GetSvc<T> {
                        type Response = super::PathInfo;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPathInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PathInfoService>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.store.v1.PathInfoService/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: PathInfoService>(pub Arc<T>);
                    impl<T: PathInfoService> tonic::server::UnaryService<super::PathInfo>
                    for PutSvc<T> {
                        type Response = super::PathInfo;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PathInfo>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PathInfoService>::put(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.store.v1.PathInfoService/CalculateNAR" => {
                    #[allow(non_camel_case_types)]
                    struct CalculateNARSvc<T: PathInfoService>(pub Arc<T>);
                    impl<
                        T: PathInfoService,
                    > tonic::server::UnaryService<::snix_castore::proto::Entry>
                    for CalculateNARSvc<T> {
                        type Response = super::CalculateNarResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<::snix_castore::proto::Entry>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PathInfoService>::calculate_nar(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CalculateNARSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.store.v1.PathInfoService/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: PathInfoService>(pub Arc<T>);
                    impl<
                        T: PathInfoService,
                    > tonic::server::ServerStreamingService<super::ListPathInfoRequest>
                    for ListSvc<T> {
                        type Response = super::PathInfo;
                        type ResponseStream = T::ListStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListPathInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PathInfoService>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PathInfoServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snix.store.v1.PathInfoService";
    impl<T> tonic::server::NamedService for PathInfoServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
