// This file is @generated by prost-build.
/// A Directory can contain Directory, File or Symlink entries.
/// Each of these nodes have a name attribute, which is the basename in that
/// directory and node type specific attributes.
/// The name attribute:
///   - MUST not contain slashes or null bytes
///   - MUST not be '.' or '..'
///   - MUST be unique across all three lists
/// Elements in each list need to be lexicographically ordered by the name
/// attribute.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Directory {
    #[prost(message, repeated, tag = "1")]
    pub directories: ::prost::alloc::vec::Vec<DirectoryEntry>,
    #[prost(message, repeated, tag = "2")]
    pub files: ::prost::alloc::vec::Vec<FileEntry>,
    #[prost(message, repeated, tag = "3")]
    pub symlinks: ::prost::alloc::vec::Vec<SymlinkEntry>,
}
/// A DirectoryEntry represents a directory.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirectoryEntry {
    /// The (base)name of the directory
    #[prost(bytes = "bytes", tag = "1")]
    pub name: ::prost::bytes::Bytes,
    /// The blake3 digest of a Directory message.
    #[prost(bytes = "bytes", tag = "2")]
    pub digest: ::prost::bytes::Bytes,
    /// Number of child elements in the Directory referred to by `digest`.
    /// Calculated by summing up the numbers of `directories`, `files` and
    /// `symlinks`, and for each directory, its size field. Used for inode number
    /// calculation.
    /// This field is precisely as verifiable as any other Merkle tree edge.
    /// Resolve `digest`, and you can compute it incrementally. Resolve the entire
    /// tree, and you can fully compute it from scratch.
    /// A credulous implementation won't reject an excessive size, but this is
    /// harmless: you'll have some ordinals without nodes. Undersizing is obvious
    /// and easy to reject: you won't have an ordinal for some nodes.
    #[prost(uint64, tag = "3")]
    pub size: u64,
}
/// A FileEntry represents a regular or executable file.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    /// The (base)name of the file
    #[prost(bytes = "bytes", tag = "1")]
    pub name: ::prost::bytes::Bytes,
    /// The blake3 digest of the file contents
    #[prost(bytes = "bytes", tag = "2")]
    pub digest: ::prost::bytes::Bytes,
    /// The file content size
    #[prost(uint64, tag = "3")]
    pub size: u64,
    /// Whether the file is executable
    #[prost(bool, tag = "4")]
    pub executable: bool,
}
/// A SymlinkEntry represents a symbolic link.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SymlinkEntry {
    /// The (base)name of the symlink
    #[prost(bytes = "bytes", tag = "1")]
    pub name: ::prost::bytes::Bytes,
    /// The target of the symlink.
    #[prost(bytes = "bytes", tag = "2")]
    pub target: ::prost::bytes::Bytes,
}
/// A Entry is either a DirectoryEntry, FileEntry or SymlinkEntry.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entry {
    #[prost(oneof = "entry::Entry", tags = "1, 2, 3")]
    pub entry: ::core::option::Option<entry::Entry>,
}
/// Nested message and enum types in `Entry`.
pub mod entry {
    #[derive(Eq, Hash)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Entry {
        #[prost(message, tag = "1")]
        Directory(super::DirectoryEntry),
        #[prost(message, tag = "2")]
        File(super::FileEntry),
        #[prost(message, tag = "3")]
        Symlink(super::SymlinkEntry),
    }
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatBlobRequest {
    /// The blake3 digest of the blob requested
    #[prost(bytes = "bytes", tag = "1")]
    pub digest: ::prost::bytes::Bytes,
    /// Whether the server should reply with a list of more granular chunks.
    #[prost(bool, tag = "2")]
    pub send_chunks: bool,
    /// Whether the server should reply with a bao.
    #[prost(bool, tag = "3")]
    pub send_bao: bool,
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatBlobResponse {
    /// If `send_chunks` was set to true, this MAY contain a list of more
    /// granular chunks, which then may be read individually via the `Read`
    /// method.
    #[prost(message, repeated, tag = "2")]
    pub chunks: ::prost::alloc::vec::Vec<stat_blob_response::ChunkMeta>,
    /// If `send_bao` was set to true, this MAY contain a outboard bao.
    /// The exact format and message types here will still be fleshed out.
    #[prost(bytes = "bytes", tag = "3")]
    pub bao: ::prost::bytes::Bytes,
}
/// Nested message and enum types in `StatBlobResponse`.
pub mod stat_blob_response {
    #[derive(Eq, Hash)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ChunkMeta {
        /// Digest of that specific chunk
        #[prost(bytes = "bytes", tag = "1")]
        pub digest: ::prost::bytes::Bytes,
        /// Length of that chunk, in bytes.
        #[prost(uint64, tag = "2")]
        pub size: u64,
    }
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadBlobRequest {
    /// The blake3 digest of the blob or chunk requested
    #[prost(bytes = "bytes", tag = "1")]
    pub digest: ::prost::bytes::Bytes,
}
/// This represents some bytes of a blob.
/// Blobs are sent in smaller chunks to keep message sizes manageable.
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobChunk {
    #[prost(bytes = "bytes", tag = "1")]
    pub data: ::prost::bytes::Bytes,
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutBlobResponse {
    /// The blake3 digest of the data that was sent.
    #[prost(bytes = "bytes", tag = "1")]
    pub digest: ::prost::bytes::Bytes,
}
/// Generated client implementations.
pub mod blob_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// BlobService allows reading (or uploading) content-addressed blobs of data.
    /// BLAKE3 is used as a hashing function for the data. Uploading a blob will
    /// return the BLAKE3 digest of it, and that's the identifier used to Read/Stat
    /// them too.
    #[derive(Debug, Clone)]
    pub struct BlobServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BlobServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BlobServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BlobServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BlobServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stat can be used to check for the existence of a blob, as well as
        /// gathering more data about it, like more granular chunking information
        /// or baos.
        /// Server implementations are not required to provide more granular chunking
        /// information, especially if the digest specified in `StatBlobRequest` is
        /// already a chunk of a blob.
        pub async fn stat(
            &mut self,
            request: impl tonic::IntoRequest<super::StatBlobRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StatBlobResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.castore.v1.BlobService/Stat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.castore.v1.BlobService", "Stat"));
            self.inner.unary(req, path, codec).await
        }
        /// Read allows reading (all) data of a blob/chunk by the BLAKE3 digest of
        /// its contents.
        /// If the backend communicated more granular chunks in the `Stat` request,
        /// this can also be used to read chunks.
        /// This request returns a stream of BlobChunk, which is just a container for
        /// a stream of bytes.
        /// The server may decide on whatever chunking it may seem fit as a size for
        /// the individual BlobChunk sent in the response stream, this is mostly to
        /// keep individual messages at a manageable size.
        pub async fn read(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadBlobRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BlobChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.castore.v1.BlobService/Read",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.castore.v1.BlobService", "Read"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Put uploads a Blob, by reading a stream of bytes.
        ///
        /// The way the data is chunked up in individual BlobChunk messages sent in
        /// the stream has no effect on how the server ends up chunking blobs up, if
        /// it does at all.
        pub async fn put(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::BlobChunk>,
        ) -> std::result::Result<
            tonic::Response<super::PutBlobResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.castore.v1.BlobService/Put",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.castore.v1.BlobService", "Put"));
            self.inner.client_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod blob_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BlobServiceServer.
    #[async_trait]
    pub trait BlobService: std::marker::Send + std::marker::Sync + 'static {
        /// Stat can be used to check for the existence of a blob, as well as
        /// gathering more data about it, like more granular chunking information
        /// or baos.
        /// Server implementations are not required to provide more granular chunking
        /// information, especially if the digest specified in `StatBlobRequest` is
        /// already a chunk of a blob.
        async fn stat(
            &self,
            request: tonic::Request<super::StatBlobRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StatBlobResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the Read method.
        type ReadStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BlobChunk, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Read allows reading (all) data of a blob/chunk by the BLAKE3 digest of
        /// its contents.
        /// If the backend communicated more granular chunks in the `Stat` request,
        /// this can also be used to read chunks.
        /// This request returns a stream of BlobChunk, which is just a container for
        /// a stream of bytes.
        /// The server may decide on whatever chunking it may seem fit as a size for
        /// the individual BlobChunk sent in the response stream, this is mostly to
        /// keep individual messages at a manageable size.
        async fn read(
            &self,
            request: tonic::Request<super::ReadBlobRequest>,
        ) -> std::result::Result<tonic::Response<Self::ReadStream>, tonic::Status>;
        /// Put uploads a Blob, by reading a stream of bytes.
        ///
        /// The way the data is chunked up in individual BlobChunk messages sent in
        /// the stream has no effect on how the server ends up chunking blobs up, if
        /// it does at all.
        async fn put(
            &self,
            request: tonic::Request<tonic::Streaming<super::BlobChunk>>,
        ) -> std::result::Result<tonic::Response<super::PutBlobResponse>, tonic::Status>;
    }
    /// BlobService allows reading (or uploading) content-addressed blobs of data.
    /// BLAKE3 is used as a hashing function for the data. Uploading a blob will
    /// return the BLAKE3 digest of it, and that's the identifier used to Read/Stat
    /// them too.
    #[derive(Debug)]
    pub struct BlobServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BlobServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BlobServiceServer<T>
    where
        T: BlobService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snix.castore.v1.BlobService/Stat" => {
                    #[allow(non_camel_case_types)]
                    struct StatSvc<T: BlobService>(pub Arc<T>);
                    impl<
                        T: BlobService,
                    > tonic::server::UnaryService<super::StatBlobRequest>
                    for StatSvc<T> {
                        type Response = super::StatBlobResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatBlobRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlobService>::stat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.castore.v1.BlobService/Read" => {
                    #[allow(non_camel_case_types)]
                    struct ReadSvc<T: BlobService>(pub Arc<T>);
                    impl<
                        T: BlobService,
                    > tonic::server::ServerStreamingService<super::ReadBlobRequest>
                    for ReadSvc<T> {
                        type Response = super::BlobChunk;
                        type ResponseStream = T::ReadStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadBlobRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlobService>::read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.castore.v1.BlobService/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: BlobService>(pub Arc<T>);
                    impl<
                        T: BlobService,
                    > tonic::server::ClientStreamingService<super::BlobChunk>
                    for PutSvc<T> {
                        type Response = super::PutBlobResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::BlobChunk>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BlobService>::put(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BlobServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snix.castore.v1.BlobService";
    impl<T> tonic::server::NamedService for BlobServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDirectoryRequest {
    /// If set to true, recursively resolve all child Directory messages.
    /// Directory messages SHOULD be streamed in a recursive breadth-first walk,
    /// but other orders are also fine, as long as Directory messages are only
    /// sent after they are referred to from previously sent Directory messages.
    #[prost(bool, tag = "2")]
    pub recursive: bool,
    #[prost(oneof = "get_directory_request::ByWhat", tags = "1")]
    pub by_what: ::core::option::Option<get_directory_request::ByWhat>,
}
/// Nested message and enum types in `GetDirectoryRequest`.
pub mod get_directory_request {
    #[derive(Eq, Hash)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ByWhat {
        /// The blake3 hash of the (root) Directory message, serialized in
        /// protobuf canonical form.
        /// Keep in mind this can be a subtree of another root.
        #[prost(bytes, tag = "1")]
        Digest(::prost::bytes::Bytes),
    }
}
#[derive(Eq, Hash)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutDirectoryResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub root_digest: ::prost::bytes::Bytes,
}
/// Generated client implementations.
pub mod directory_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct DirectoryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DirectoryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DirectoryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DirectoryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DirectoryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get retrieves a stream of Directory messages, by using the lookup
        /// parameters in GetDirectoryRequest.
        /// Keep in mind multiple DirectoryNodes in different parts of the graph might
        /// have the same digest if they have the same underlying contents,
        /// so sending subsequent ones can be omitted.
        ///
        /// It is okay for certain implementations to only allow retrieval of
        /// Directory digests that are at the "root", aka the last element that's
        /// sent in a Put. This makes sense for implementations bundling closures of
        /// directories together in batches.
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDirectoryRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Directory>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.castore.v1.DirectoryService/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.castore.v1.DirectoryService", "Get"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Put uploads a graph of Directory messages.
        /// Individual Directory messages need to be send in an order walking up
        /// from the leaves to the root - a Directory message can only refer to
        /// Directory messages previously sent in the same stream.
        /// Keep in mind multiple DirectoryNodes in different parts of the graph might
        /// have the same digest if they have the same underlying contents,
        /// so sending subsequent ones can be omitted.
        /// We might add a separate method, allowing to send partial graphs at a later
        /// time, if requiring to send the full graph turns out to be a problem.
        pub async fn put(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::Directory>,
        ) -> std::result::Result<
            tonic::Response<super::PutDirectoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.castore.v1.DirectoryService/Put",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.castore.v1.DirectoryService", "Put"));
            self.inner.client_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod directory_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DirectoryServiceServer.
    #[async_trait]
    pub trait DirectoryService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Get method.
        type GetStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Directory, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Get retrieves a stream of Directory messages, by using the lookup
        /// parameters in GetDirectoryRequest.
        /// Keep in mind multiple DirectoryNodes in different parts of the graph might
        /// have the same digest if they have the same underlying contents,
        /// so sending subsequent ones can be omitted.
        ///
        /// It is okay for certain implementations to only allow retrieval of
        /// Directory digests that are at the "root", aka the last element that's
        /// sent in a Put. This makes sense for implementations bundling closures of
        /// directories together in batches.
        async fn get(
            &self,
            request: tonic::Request<super::GetDirectoryRequest>,
        ) -> std::result::Result<tonic::Response<Self::GetStream>, tonic::Status>;
        /// Put uploads a graph of Directory messages.
        /// Individual Directory messages need to be send in an order walking up
        /// from the leaves to the root - a Directory message can only refer to
        /// Directory messages previously sent in the same stream.
        /// Keep in mind multiple DirectoryNodes in different parts of the graph might
        /// have the same digest if they have the same underlying contents,
        /// so sending subsequent ones can be omitted.
        /// We might add a separate method, allowing to send partial graphs at a later
        /// time, if requiring to send the full graph turns out to be a problem.
        async fn put(
            &self,
            request: tonic::Request<tonic::Streaming<super::Directory>>,
        ) -> std::result::Result<
            tonic::Response<super::PutDirectoryResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct DirectoryServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> DirectoryServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for DirectoryServiceServer<T>
    where
        T: DirectoryService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snix.castore.v1.DirectoryService/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: DirectoryService>(pub Arc<T>);
                    impl<
                        T: DirectoryService,
                    > tonic::server::ServerStreamingService<super::GetDirectoryRequest>
                    for GetSvc<T> {
                        type Response = super::Directory;
                        type ResponseStream = T::GetStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDirectoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DirectoryService>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/snix.castore.v1.DirectoryService/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: DirectoryService>(pub Arc<T>);
                    impl<
                        T: DirectoryService,
                    > tonic::server::ClientStreamingService<super::Directory>
                    for PutSvc<T> {
                        type Response = super::PutDirectoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::Directory>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DirectoryService>::put(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for DirectoryServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snix.castore.v1.DirectoryService";
    impl<T> tonic::server::NamedService for DirectoryServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
