// This file is @generated by prost-build.
/// A BuildRequest describes the request of something to be run on the builder.
/// It is distinct from an actual \[Build\] that has already happened, or might be
/// currently ongoing.
///
/// A BuildRequest can be seen as a more normalized version of a Derivation
/// (parsed from A-Term), "writing out" some of the Nix-internal details about
/// how e.g. environment variables in the build are set.
///
/// Nix has some impurities when building a Derivation, for example the --cores option
/// ends up as an environment variable in the build, that's not part of the ATerm.
///
/// As of now, we serialize this into the BuildRequest, so builders can stay dumb.
/// This might change in the future.
///
/// There's also a big difference when it comes to how inputs are modelled:
///   - Nix only uses store path (strings) to describe the inputs.
///     As store paths can be input-addressed, a certain store path can contain
///     different contents (as not all store paths are binary reproducible).
///     This requires that for every input-addressed input, the builder has access
///     to either the input's deriver (and needs to build it) or else a trusted
///     source for the built input.
///     to upload input-addressed paths, requiring the trusted users concept.
///   - snix-build records a list of snix.castore.v1.Node as inputs.
///     These map from the store path base name to their contents, relieving the
///     builder from having to "trust" any input-addressed paths, contrary to Nix.
///
/// While this approach gives a better hermeticity, it has one downside:
/// A BuildRequest can only be sent once the contents of all its inputs are known.
///
/// As of now, we're okay to accept this, but it prevents uploading an
/// entirely-non-IFD subgraph of BuildRequests eagerly.
///
/// FUTUREWORK: We might be introducing another way to refer to inputs, to
/// support "send all BuildRequest for a nixpkgs eval to a remote builder and put
/// the laptop to sleep" usecases later.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildRequest {
    /// The list of all root nodes that should be visible in `inputs_dir` at the
    /// time of the build.
    /// As all references are content-addressed, no additional signatures are
    /// needed to substitute / make these available in the build environment.
    /// Inputs MUST be sorted by their names.
    #[prost(message, repeated, tag = "1")]
    pub inputs: ::prost::alloc::vec::Vec<::snix_castore::proto::Entry>,
    /// The command (and its args) executed as the build script.
    /// In the case of a Nix derivation, this is usually
    /// \["/path/to/some-bash/bin/bash", "-e", "/path/to/some/builder.sh"\].
    #[prost(string, repeated, tag = "2")]
    pub command_args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The working dir of the command, relative to the build root.
    /// "build", in the case of Nix.
    /// This MUST be a clean relative path, without any ".", "..", or superfluous
    /// slashes.
    #[prost(string, tag = "3")]
    pub working_dir: ::prost::alloc::string::String,
    /// A list of "scratch" paths, relative to the build root.
    /// These will be write-able during the build.
    /// \[build, nix/store\] in the case of Nix.
    /// These MUST be clean relative paths, without any ".", "..", or superfluous
    /// slashes, and sorted.
    #[prost(string, repeated, tag = "4")]
    pub scratch_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The path where the castore input nodes will be located at,
    /// "nix/store" in case of Nix.
    /// Builds might also write into here (Nix builds do that).
    /// This MUST be a clean relative path, without any ".", "..", or superfluous
    /// slashes.
    #[prost(string, tag = "5")]
    pub inputs_dir: ::prost::alloc::string::String,
    /// The list of output paths the build is expected to produce,
    /// relative to the root.
    /// If the path is not produced, the build is considered to have failed.
    /// These MUST be clean relative paths, without any ".", "..", or superfluous
    /// slashes, and sorted.
    #[prost(string, repeated, tag = "6")]
    pub outputs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The list of environment variables and their values that should be set
    /// inside the build environment.
    /// This includes both environment vars set inside the derivation, as well as
    /// more "ephemeral" ones like NIX_BUILD_CORES, controlled by the `--cores`
    /// CLI option of `nix-build`.
    /// For now, we consume this as an option when turning a Derivation into a BuildRequest,
    /// similar to how Nix has a `--cores` option.
    /// We don't want to bleed these very nix-specific sandbox impl details into
    /// (dumber) builders if we don't have to.
    /// Environment variables are sorted by their keys.
    #[prost(message, repeated, tag = "7")]
    pub environment_vars: ::prost::alloc::vec::Vec<build_request::EnvVar>,
    /// A set of constraints that need to be satisfied on a build host before a
    /// Build can be started.
    #[prost(message, optional, tag = "8")]
    pub constraints: ::core::option::Option<build_request::BuildConstraints>,
    /// Additional (small) files and their contents that should be placed into the
    /// build environment, but outside inputs_dir.
    /// Used for passAsFile and structuredAttrs in Nix.
    #[prost(message, repeated, tag = "9")]
    pub additional_files: ::prost::alloc::vec::Vec<build_request::AdditionalFile>,
    /// If this is an non-empty list, all paths in `outputs` are scanned for these.
    /// For Nix, `refscan_needles` would be populated with the nixbase32 hash parts of
    /// every input store path and output store path. The latter is necessary to scan
    /// for references between multi-output derivations.
    #[prost(string, repeated, tag = "10")]
    pub refscan_needles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Nested message and enum types in `BuildRequest`.
pub mod build_request {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EnvVar {
        /// name of the environment variable. Must not contain = or \0.
        #[prost(string, tag = "1")]
        pub key: ::prost::alloc::string::String,
        /// value of the environment variable. Must not contain \0.
        #[prost(bytes = "bytes", tag = "2")]
        pub value: ::prost::bytes::Bytes,
    }
    /// BuildConstraints represents certain conditions that must be fulfilled
    /// inside the build environment to be able to build this.
    /// Constraints can be things like required architecture and minimum amount of memory.
    /// The required input paths are *not* represented in here, because it
    /// wouldn't be hermetic enough - see the comment around inputs too.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BuildConstraints {
        /// The system that's needed to execute the build.
        /// Must not be empty.
        #[prost(string, tag = "1")]
        pub system: ::prost::alloc::string::String,
        /// The amount of memory required to be available for the build, in bytes.
        #[prost(uint64, tag = "2")]
        pub min_memory: u64,
        /// A list of (absolute) paths that need to be available in the build
        /// environment, like `/dev/kvm`.
        /// This is distinct from the castore nodes in inputs.
        /// TODO: check if these should be individual constraints instead.
        /// These MUST be clean absolute paths, without any ".", "..", or superfluous
        /// slashes, and sorted.
        #[prost(string, repeated, tag = "3")]
        pub available_ro_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
        /// Whether the build should be able to access the network,
        #[prost(bool, tag = "4")]
        pub network_access: bool,
        /// Whether to provide a /bin/sh inside the build environment, usually a static bash.
        #[prost(bool, tag = "5")]
        pub provide_bin_sh: bool,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AdditionalFile {
        #[prost(string, tag = "1")]
        pub path: ::prost::alloc::string::String,
        #[prost(bytes = "bytes", tag = "2")]
        pub contents: ::prost::bytes::Bytes,
    }
}
/// A BuildResponse is (one possible) outcome of executing a \[BuildRequest\].
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuildResponse {
    /// The outputs that were produced after successfully building.
    /// They are provided in the same order as specified in the \[BuildRequest\].
    #[prost(message, repeated, tag = "1")]
    pub outputs: ::prost::alloc::vec::Vec<build_response::Output>,
}
/// Nested message and enum types in `BuildResponse`.
pub mod build_response {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Output {
        /// Output entry produced by the build. It may not contain a name,
        /// as not all OS paths can be represented as castore paths.
        /// The path this was ingested from can be looked up in the original build request.
        #[prost(message, optional, tag = "1")]
        pub output: ::core::option::Option<::snix_castore::proto::Entry>,
        /// Indexes into the found \[BuildRequest::refscan_needles\] in this output.
        #[prost(uint64, repeated, tag = "2")]
        pub needles: ::prost::alloc::vec::Vec<u64>,
    }
}
/// Generated client implementations.
pub mod build_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct BuildServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BuildServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BuildServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BuildServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BuildServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn do_build(
            &mut self,
            request: impl tonic::IntoRequest<super::BuildRequest>,
        ) -> std::result::Result<tonic::Response<super::BuildResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/snix.build.v1.BuildService/DoBuild",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("snix.build.v1.BuildService", "DoBuild"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod build_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BuildServiceServer.
    #[async_trait]
    pub trait BuildService: std::marker::Send + std::marker::Sync + 'static {
        async fn do_build(
            &self,
            request: tonic::Request<super::BuildRequest>,
        ) -> std::result::Result<tonic::Response<super::BuildResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct BuildServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BuildServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BuildServiceServer<T>
    where
        T: BuildService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/snix.build.v1.BuildService/DoBuild" => {
                    #[allow(non_camel_case_types)]
                    struct DoBuildSvc<T: BuildService>(pub Arc<T>);
                    impl<
                        T: BuildService,
                    > tonic::server::UnaryService<super::BuildRequest>
                    for DoBuildSvc<T> {
                        type Response = super::BuildResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BuildRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BuildService>::do_build(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DoBuildSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BuildServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "snix.build.v1.BuildService";
    impl<T> tonic::server::NamedService for BuildServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
