# Installer - Redox filesystem builder (host tool)
#
# Creates Redox filesystem images from directory trees.
# Runs on the host machine (not cross-compiled).
#
# Note: Uses ring from crates.io instead of git to get pregenerated assembly.

{
  pkgs,
  lib,
  rustToolchain,
  src,
  ...
}:

let
  # Fetch ring 0.17.8 from crates.io with pregenerated assembly files
  ringCrate = pkgs.fetchurl {
    url = "https://crates.io/api/v1/crates/ring/0.17.8/download";
    sha256 = "sha256-wX+ky2WONYNCPpFbnzrMAczq7hhg4z1Z665mrcOi3A0=";
  };

  # Patch source to use local ring instead of git
  patchedSrc = pkgs.stdenv.mkDerivation {
    name = "installer-src-patched";
    inherit src;

    phases = [
      "unpackPhase"
      "patchPhase"
      "installPhase"
    ];

    patchPhase = ''
      runHook prePatch

      # Extract ring crate from crates.io (has pregenerated assembly files)
      mkdir -p deps
      tar -xzf ${ringCrate} -C deps
      mv deps/ring-0.17.8 deps/ring

      # Replace the git URL in [patch.crates-io] with a local path
      sed -i 's|ring = { git = "https://gitlab.redox-os.org/redox-os/ring.git", branch = "redox-0.17.8" }|ring = { path = "deps/ring" }|' Cargo.toml

      runHook postPatch
    '';

    installPhase = ''
      cp -r . $out
    '';
  };

  # Vendor dependencies
  installerVendor = pkgs.rustPlatform.fetchCargoVendor {
    name = "installer-cargo-vendor";
    src = patchedSrc;
    hash = "sha256-UsSs0zyZnrZAmhgUPAkWoQ3vOAecdm4DPW+EpM+uvjI=";
  };

in
pkgs.stdenv.mkDerivation {
  pname = "redox-installer";
  version = "unstable";

  src = patchedSrc;

  nativeBuildInputs = [
    rustToolchain
    pkgs.pkg-config
  ];

  buildInputs = with pkgs; [
    fuse
    fuse3
  ];

  configurePhase = ''
    runHook preConfigure

    mkdir -p .cargo
    # Use the cargo config generated by fetchCargoVendor, replacing @vendor@
    sed "s|@vendor@|${installerVendor}|g" ${installerVendor}/.cargo/config.toml > .cargo/config.toml
    cat >> .cargo/config.toml << EOF

    [net]
    offline = true
    EOF

    export HOME=$(mktemp -d)

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild

    cargo build --release

    runHook postBuild
  '';

  doCheck = true;

  checkPhase = ''
    runHook preCheck

    cargo test --release || echo "No tests found (expected for installer)"

    runHook postCheck
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin
    cp target/release/redox_installer $out/bin/
    cp target/release/redox_installer_tui $out/bin/ 2>/dev/null || true

    runHook postInstall
  '';

  meta = with lib; {
    description = "Redox OS Installer - filesystem image builder";
    homepage = "https://gitlab.redox-os.org/redox-os/installer";
    license = licenses.mit;
    platforms = platforms.linux;
    mainProgram = "redox_installer";
  };
}
