# gdb-protocol - GDB Remote Serial Protocol implementation
#
# Library crate implementing the GDB RSP for building debug stubs.
# Only dependency is memchr. Produces a Redox library.
# Source has no Cargo.lock (lib crate) — we inject one in preConfigure.
#
# Source: gitlab.redox-os.org/redox-os/gdb-protocol

{
  pkgs,
  lib,
  rustToolchain,
  sysrootVendor,
  redoxTarget,
  relibc,
  stubLibs,
  vendor,
  gdb-protocol-src,
  ...
}:

let
  mkUserspace = import ./mk-userspace.nix {
    inherit
      pkgs
      lib
      rustToolchain
      sysrootVendor
      redoxTarget
      relibc
      stubLibs
      vendor
      ;
  };

  # Generate Cargo.lock since the library crate doesn't ship one
  srcWithLock = pkgs.runCommand "gdb-protocol-src-with-lock" { } ''
    cp -r ${gdb-protocol-src} $out
    chmod -R u+w $out
    cat > $out/Cargo.lock << 'EOF'
    # Generated by cargo for gdb-protocol 0.1.0
    version = 3

    [[package]]
    name = "gdb-protocol"
    version = "0.1.0"
    dependencies = [
     "memchr",
    ]

    [[package]]
    name = "memchr"
    version = "2.7.4"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "78ca9ab1a0babb1e7d5695e3530886289c18cf2f87ec19a575a0abdce112e3a3"
    EOF
  '';

in
mkUserspace.mkPackage {
  pname = "gdb-protocol";
  src = srcWithLock;
  vendorHash = "sha256-ee3KhyqCCHDi3xbM+eiLOhUL2aFxp+T043+PGXRFU4Q=";
  cargoBuildFlags = "--lib";

  installPhase = ''
    runHook preInstall
    mkdir -p $out/lib
    find target/${redoxTarget}/release -maxdepth 1 \
      \( -name "*.rlib" -o -name "*.a" \) \
      -exec cp {} $out/lib/ \;
    runHook postInstall
  '';

  meta = with lib; {
    description = "GDB Remote Serial Protocol implementation for Redox OS";
    homepage = "https://gitlab.redox-os.org/redox-os/gdb-protocol";
    license = licenses.mit;
  };
}
